### ISSUE TITLE
Suggestion for CSS code formatting.

### ISSUE THREAD

**Issue by josephtkim** [kishore1999/prj-rev-bwfs-dasmoto#5]
For best practices, it is good to place place the selector name, and the opening { on the same line. In addition, it can be a good idea to place an empty line between each selector to make the code easier to read. For instance,

```css
h1 {
  font-family: Helvetica;
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg")
}

.brush {
  font-family: Helvetica;
  font-size: 30px;
  font-weight: bold;
  color: white;
  background-color: mediumspringgreen;
}
```
