### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [kishore1999/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. There are several shared properties among the selectors, which can be simplified like so

```css
h1, h2, p {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 30px;
  color: white;
}
```
